### PR TITLE
Fix C++ compilation warning

### PR DESCRIPTION
**Pull request by ondrapCZE**

### CODE REVIEW

**Comment by JimTrudeau** [comment]
Greetings! Thanks for the PR!

"Technically" we aren't supporting PRs yet. We will enable that shortly, with a CONTRIBUTING.md, a PR template, and all the usual goodies.

In the meantime, engineering has reviewed. This fix is already in queue, we're going to be releasing in a few days. We do not develop code on GitHub, we use it as a delivery vehicle. So these changes will not be merged into the master branch. They would be brought into our internal systems and applied to the developing code base.

I'll go over this with the engineering lead. In the meantime, based on his feedback I'm going to tag this as "approved." As noted, the PR will eventually be closed without merging into master, but that doesn't mean it doesn't happen.

Thanks again!

**Comment by ondrapCZE** [comment]
Hi Jim,

I am not expecting that it will be merged on the github like others
projects do it ;). For us this is the easiest way how to make bugfixes
and share them back with you. We have forked your repositories because
of these bugfixes and therefore it is more convenient for us to make PR
back to lower your work. I am glad that it helps.

Is it possible to be in closer loop with new releases or maybe some pre
releases?

Currently we are porting our code from Creator PDL to Modus one.
Unfortunately official release doesn't support ale features of the
Creator PDL like BLE controller on the M0p with a custom code. I am
solving this issue via MyCases but it will be nicer to have such thing
in the repo not outside of it in a folder temporary. 

Regards

Ondrej

Dne 3/24/2020 v 7:50 PM Jim Trudeau napsal(a):

**Comment by JimTrudeau** [comment]
Ondrej, not sure what you mean by "Is it possible to be in closer loop with new releases or maybe some prereleases?" In this case it is any day. We have final release candidates internally, and barring the unexpected it's real soon.  I have always been reluctant to make promises, knowing what happens to engineering schedules. If you have an FAE you work with, that's a good question for them. I think (not positive) that the future has bless entirely on one chip or the other, not split. But don't hold me to that.

**Comment by JimTrudeau** [comment]
Fix implemented in https://github.com/cypresssemiconductorco/core-lib/releases/tag/release-v1.1.2

Closing. Thanks again.

**Pull request closed without merging**
